default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: fukurou_app_development
  username: fukuchan
  password: ""
  host: localhost

test:
  <<: *default
  database: fukurou_app_test
  username: fukuchan
  password: ""
  host: localhost

production:
  <<: *default
  database: fukurou_app_production
  username: fukuchan
  password: "fukuchan123"
  host: localhost
  port: 5432

# Rails 8 Action Cable設定
cable:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: fukurou_app_production
  username: fukuchan
  password: "fukuchan123"
  host: localhost
  port: 5432

# Rails 8 Solid Queue設定
queue:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: fukurou_app_production
  username: fukuchan
  password: "fukuchan123"
  host: localhost
  port: 5432

# Rails 8 Solid Cache設定（新登場！）
cache:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: fukurou_app_production
  username: fukuchan
  password: "fukuchan123"
  host: localhost
  port: 5432